#------------------------------------------------------------------------------
# Aliases setup
#------------------------------------------------------------------------------
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"

## Folder direct access
alias memex="cd ~/Dropbox/memex"
alias dot="cd ~/dotfiles"

# Install another copy of Homebrew for Intel simulated terminal
# https://laict.medium.com/install-homebrew-on-macos-11-apple-silicon-630f37a74490
alias ibrew='arch -x86_64 /usr/local/bin/brew'

# +----------------------------------------------------------------------------
# | Kitty
# +----------------------------------------------------------------------------
alias icat="kitty +kitten icat"
w

# Load other bashrc settings that is shared between macOS and Ubuntu
[ -f "$HOME/.shared_bashrc" ] && source "$HOME/.shared_bashrc"

# +----------------------------------------------------------------------------
# | uv (Python Package Manager)
# +----------------------------------------------------------------------------
# uv doesn't require shell initialization like pyenv
# Python versions and environments are managed via uv commands


# BEGIN_KITTY_SHELL_INTEGRATION
if test -n "$KITTY_INSTALLATION_DIR" -a -e "$KITTY_INSTALLATION_DIR/shell-integration/bash/kitty.bash"; then source "$KITTY_INSTALLATION_DIR/shell-integration/bash/kitty.bash"; fi
# END_KITTY_SHELL_INTEGRATION

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
