#------------------------------------------------------------------------------
# Aliases setup
#------------------------------------------------------------------------------
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"

## Folder direct access
alias memex="cd ~/Library/Mobile\ Documents/iCloud~md~obsidian/Documents/memex"

# Install another copy of Homebrew for Intel simulated terminal
# https://laict.medium.com/install-homebrew-on-macos-11-apple-silicon-630f37a74490
alias ibrew='arch -x86_64 /usr/local/bin/brew'

# +----------------------------------------------------------------------------
# | Kitty
# +----------------------------------------------------------------------------
alias icat="kitty +kitten icat"



# Load other bashrc settings that is shared between macOS and Ubuntu
[ -f "$HOME/.shared_bashrc" ] && source "$HOME/.shared_bashrc"

# +----------------------------------------------------------------------------
# | Pyenv
# +----------------------------------------------------------------------------
eval "$(pyenv init -)"


# BEGIN_KITTY_SHELL_INTEGRATION
if test -n "$KITTY_INSTALLATION_DIR" -a -e "$KITTY_INSTALLATION_DIR/shell-integration/bash/kitty.bash"; then source "$KITTY_INSTALLATION_DIR/shell-integration/bash/kitty.bash"; fi
# END_KITTY_SHELL_INTEGRATION
