#!/bin/bash

# +----------------------------------------------------------------------------
# | Environment variables
# +----------------------------------------------------------------------------
# Silence the warning in macOS Catalina
# Read: https://support.apple.com/en-hk/HT208050
export BASH_SILENCE_DEPRECATION_WARNING=1

# Tell ls to be colourful
export CLICOLOR=1
export LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD

# Custom bash prompt
parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

export PS1='\[\e[0;37m\]\u\[\e[0;33m\]@\[\e[1;31m\]\h\[\e[0;37m\]:\[\e[0;32m\]\w\[\e[0;32m\]\[\e[0;38m\]$(parse_git_branch)\n\[\e[0;32m\]\$\[\e[0;37m\] '

export PATH=$PATH
export PATH=$HOME/bin:$PATH
export PATH=/usr/bin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/sbin:$PATH

# Following settings comes from hackercodex.com
# Set architecture flags
export ARCHFLAGS="-arch x86_64"

# Locale
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"

# For Homebrew's openssl
export PATH="/usr/local/opt/openssl/bin:$PATH"

### zlib (Homebrew's keg)
# For compilers to find zlib you may need to set:
export LDFLAGS="-L/usr/local/opt/zlib/lib"
export CPPFLAGS="-I/usr/local/opt/zlib/include"

# For pkg-config to find zlib you may need to set:
# export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"

# +----------------------------------------------------------------------------
# | Google Cloud SDk
# +----------------------------------------------------------------------------
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc'
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc'

# +----------------------------------------------------------------------------
# | RVM
# +----------------------------------------------------------------------------
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Load other profile settings that is shared between macOS and Ubuntu
[ -f "$HOME/.shared_profile" ] && source "$HOME/.shared_profile"

# +----------------------------------------------------------------------------
# | Homebrew on M1
# +----------------------------------------------------------------------------
# https://stackoverflow.com/a/68494567/2282592
export PATH=/opt/homebrew/bin:$PATH
