# export ZDORDIR="~/dotfiles/zsh"

# +----------------------------------------------------------------------------
# | Default path
# +----------------------------------------------------------------------------
# Initialize PATH variable
export PATH="$PATH"

# Update PATH variable
export PATH="$HOME/bin:$PATH"
export PATH="/usr/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"

# +----------------------------------------------------------------------------
# | Environment variables
# +----------------------------------------------------------------------------
export GIT_EDITOR=nvim
export VISUAL=nvim
export EDITOR=nvim

# +----------------------------------------------------------------------------
# | Homebrew
# +----------------------------------------------------------------------------
# For M1, see https://stackoverflow.com/a/68494567/2282592
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"

# For Homebrew's openssl
export PATH="/usr/local/opt/openssl/bin:$PATH"

# zlib (Homebrew's keg)
# For compilers to find zlib you may need to set:
export LDFLAGS="-L/usr/local/opt/zlib/lib"
export CPPFLAGS="-I/usr/local/opt/zlib/include"

# For pkg-config to find zlib you may need ot set:
export PKG_CONFIG_PATH="/opt/homebrew/opt/zlib/lib/pkgconfig"

# +----------------------------------------------------------------------------
# | Pyenv
# +----------------------------------------------------------------------------
# See https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"

# +----------------------------------------------------------------------------
# | Volta (JavaScript Tool Manager)
# +----------------------------------------------------------------------------
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
