# export ZDORDIR="~/dotfiles/zsh"

# +----------------------------------------------------------------------------
# | Default
# +----------------------------------------------------------------------------
# Initialize PATH variable
export PATH="$PATH"

# Update PATH variable
export PATH="$HOME/bin:$PATH"
export PATH="/usr/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"

# +----------------------------------------------------------------------------
# | Homebrew
# +----------------------------------------------------------------------------
# For M1, see https://stackoverflow.com/a/68494567/2282592
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"

# For Homebrew's openssl
export PATH="/usr/local/opt/openssl/bin:$PATH"

# +----------------------------------------------------------------------------
# | Pyenv
# +----------------------------------------------------------------------------
# See https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
