# export ZDORDIR="~/dotfiles/zsh"

# Initialize PATH variable
export PATH="$PATH"

# Update PATH variable
export PATH="$HOME/bin:$PATH"
export PATH="/usr/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"

# For Homebrew's openssl
export PATH="/usr/local/opt/openssl/bin:$PATH"
