# +----------------------------------------------------------------------------
# | Secrets (not in version control)
# +----------------------------------------------------------------------------
[ -f ~/.secrets ] && source ~/.secrets

# +----------------------------------------------------------------------------
# | Pretty prompt
# +----------------------------------------------------------------------------
parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

setopt PROMPT_SUBST
export PROMPT='%F{white}%n%f%F{yellow}@%F{red}%m%f%F{white}:%F{green}%~%f%F{blue}$(parse_git_branch)
%F{green}%#%f '

# +----------------------------------------------------------------------------
# | Aliases setup (System)
# +----------------------------------------------------------------------------
## Editor
alias vim="nvim"
alias vi="nvim"

## Safety
alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i"
set -o noclobber

## Listing, directories, and motion
alias ls="ls --color"
alias ll="ls -alrtF"
alias la="ls -A"
alias l="ls -CF"
alias ..="cd .."
alias ...="cd ..; cd .."
alias md="mkdir"
alias cl="clear"
alias du="du -ch"
alias treeacl="tree -A -C -L 2"

## Homebrew
alias brew-all="brew update && brew upgrade && brew cleanup"
# `brew cu` command comes from 'https://github.com/buo/homebrew-cask-upgrade'
alias brew-cask-all="brew cu -a -y --cleanup"

## Network
alias lsp="lsof -i -n -P | grep LISTEN"

## youtube-dl https://superuser.com/a/1554749
unsetopt nomatch

#------------------------------------------------------------------------------
# Aliases setup (Others)
#------------------------------------------------------------------------------
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"

## Folder direct access
alias memex="cd ~/Dropbox/memex"
alias dot="cd ~/dotfiles"

# Install another copy of Homebrew for Intel simulated terminal
# https://laict.medium.com/install-homebrew-on-macos-11-apple-silicon-630f37a74490
alias ibrew='arch -x86_64 /usr/local/bin/brew'

alias icat="kitty +kitten icat"

# +----------------------------------------------------------------------------
# | fzf
# +----------------------------------------------------------------------------
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Setup fzf
# ---------
if [[ ! "$PATH" == */opt/homebrew/opt/fzf/bin* ]]; then
  PATH="${PATH:+${PATH}:}/opt/homebrew/opt/fzf/bin"
fi

# Auto-completion
# ---------------
source "/opt/homebrew/opt/fzf/shell/completion.zsh"

# Key bindings
# ------------
source "/opt/homebrew/opt/fzf/shell/key-bindings.zsh"


# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!{.git,node_modules,.mypy_cache,__pycache__}/*" 2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# +----------------------------------------------------------------------------
# | Claude
# +----------------------------------------------------------------------------
[ -f ~/.claude_config ] && source ~/.claude_config

# +----------------------------------------------------------------------------
# | uv (Python Package Manager)
# +----------------------------------------------------------------------------
# uv doesn't require shell initialization like pyenv
# Python versions and environments are managed via uv commands
